// backend/Models/Question.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic; // For List<string>

namespace backend.Models
{
    public class Question
    {
        [Key]
        public Guid Id { get; set; } // Primary key for the question

        [Required]
        [StringLength(255)]
        public string Country { get; set; } = string.Empty;

        [Required]
        [StringLength(255)]
        public string ExamType { get; set; } = string.Empty;

        [StringLength(255)]
        public string? Stream { get; set; } // Nullable, as not all exam types have a stream

        [StringLength(255)]
        public string? Subject { get; set; } // Nullable, especially for Grade 5

        [StringLength(255)]
        public string? PaperType { get; set; } // Nullable, depending on subject/exam type

        [Required]
        [StringLength(255)]
        public string PaperCategory { get; set; } = string.Empty;

        public int? Year { get; set; } // Nullable, for 'PastPaper' category

        [StringLength(255)]
        public string? Term { get; set; } // Nullable, for 'TermTest' category

        [StringLength(500)]
        public string? SchoolName { get; set; } // Nullable, for 'TermTest' category

        [StringLength(255)]
        public string? Uploader { get; set; } // Optional uploader name

        [Required]
        public string FileUrl { get; set; } = string.Empty; // URL to the uploaded image/document

        [StringLength(255)]
        public string? FilePublicId { get; set; } // Public ID from Cloudinary (for deletion/management)

        public DateTime UploadDate { get; set; } = DateTime.UtcNow; // When the question was uploaded
        
        // Add a unique key for questions (e.g., Q-SL-AL-MATH-P1-2023)
        // This will be generated by the KeyGenerator service
        [StringLength(500)]
        public string? UniqueKey { get; set; } 
    }
}